package com.example.spi.authenticator;

import java.util.logging.Logger;
import org.keycloak.authentication.AuthenticationFlowContext;
import org.keycloak.authentication.AuthenticationFlowError;
import org.keycloak.authentication.Authenticator;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.RealmModel;
import org.keycloak.models.UserModel;

/**
 * SPI: Custom Authenticator — Account Approval Check if custom attribute "account.approved = true"
 *
 * SETUP:
 * - deploy JAR
 * - open admin console
 * - Authentication -> Flows -> duplicate "browser" flow, name it "browser-with-approval"
 * - At the "Forms" level add "+" step -> select "Account Approval Check" and set this "Required"
 * - Go back to Authentication and bind this new flow as browser flow
 * - Under Realm Settings -> User profile -> Create Attribute -> Name: account.approved , Dispaly name: "Account Approved"
 * - Now you see this attribute under a user and if you set it to "true" it will let you login
 * - Set this to "false" or null to test the block on login
 */
public class AccountApprovalAuthenticator implements Authenticator {

    private static final Logger log = Logger.getLogger(AccountApprovalAuthenticator.class.getName());

    // The user attribute key we check. Set this on a user in the Admin Console.
    public static final String ATTRIBUTE_KEY = "account.approved";

    @Override
    public void authenticate(AuthenticationFlowContext context) {
        UserModel user = context.getUser();

        if (user == null) {
            context.attempted();
            return;
        }

        String approved = user.getFirstAttribute(ATTRIBUTE_KEY);

        if ("true".equalsIgnoreCase(approved)) {
            log.info(String.format("[AccountApproval] ALLOWED — user=%s realm=%s", user.getUsername(), context.getRealm().getName()));
            context.success();
        } else {
            log.warning(String.format("[AccountApproval] DENIED — user=%s realm=%s attribute=%s", user.getUsername(), context.getRealm().getName(), approved));

            // INVALID_USER gives a generic "Invalid username or password" to avoid leaking if the account exists or not.
            context.failure(AuthenticationFlowError.INVALID_USER);
        }
    }

    @Override
    public void action(AuthenticationFlowContext context) {
        // Called when the user submits a form generated by a challenge() response - not in use.
    }

    @Override
    public boolean requiresUser() {
        return true; // true = Keycloak must resolve the user identity before calling authenticate().
    }

    @Override
    public boolean configuredFor(KeycloakSession session, RealmModel realm, UserModel user) {
        return true; // true = authenticator always considered "configured".
    }

    @Override
    public void setRequiredActions(KeycloakSession session, RealmModel realm, UserModel user) {
        // guides the user through setting up the authenticator - not in use.
    }

    @Override
    public void close() {
        // on close - no resources to release at this stage.
    }
}
