server.port=8080

# -----------------------------------------------------------------------
# The 'iss' claim inside each token must match this URI exactly.
# -----------------------------------------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/notes-realm
